//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orarend_DAL_Konzol
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cnOrarendek : DbContext
    {
        public cnOrarendek()
            : base("name=cnOrarendek")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<enTantargy> enTantargyak { get; set; }
        public virtual DbSet<enOktato> enOktatok { get; set; }
        public virtual DbSet<enTanterem> enTantermek { get; set; }
        public virtual DbSet<enBeadando> enBeadandok { get; set; }
        public virtual DbSet<enTanora> enTanorak { get; set; }
    }
}
