//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orarend_DAL_Konzol
{
    using System;
    using System.Collections.Generic;
    
    public partial class enBeadando
    {
        public int Id { get; set; }
        public System.DateTime Hatarido { get; set; }
        public string Leírás { get; set; }
        public string Tipus { get; set; }
    
        public virtual enTantargy enTantargyak { get; set; }
    }
}
