//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orarend_DAL_Konzol
{
    using System;
    using System.Collections.Generic;
    
    public partial class enTanterem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public enTanterem()
        {
            this.enTanora = new HashSet<enTanora>();
        }
    
        public int Id { get; set; }
        public string Tanterem_neve { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enTanora> enTanora { get; set; }
    }
}
